americanexpress/jest-image-snapshot

- README.md
- __tests__/src/__snapshots__/index.spec.js.snap
- __tests__/src/index.spec.js
- src/index.js
Using some jasmine/jest reporters (for example jasmine-trx-reporter) will fail because of using chalk.
chalk doesn't realize the terminal doesn't support color.
This adds the option for the outcome of the test would not have styling inside of it.
> Add noColors option to matcher

- README.md
* master branch for the build badge, though for publishes maybe each version should generate the `README` and use the tag?
* kept the badges on the same line, but also tried to make the markdown a bit readable: avoided having a very long line
> docs(README): adds TravisCI build badge

- README.md
- __tests__/src/index.spec.js
- src/index.js
Use case: I'd like to have default configuration - in particular, I'd like to set change the default configuration to 0% threshold so all nonzero diffs fail.
This PR provides a non-breaking addition that adds a configurable export (via a higher-order function) from the package.
> Allow for a common default configuration

- README.md
The group level links don't seem to work anymore, updating to repo specific link
> chore(README): update CLA assistant address

- README.md
This updates the README to address some confusion I had with #29.
> Mentions in README that customSnapshotsDir is absolute path

- .travis.yml
- package.json
- src/diff-snapshot.js
Since node 9, PNG._packer._handle.jsref has a circular reference, causing JSON.stringify to fail. Since none of the hidden properties starting with _ aren't needed for writing the images, I went ahead and discarded them all.
> fix(diff-snapshot): Fix stringify failure due to circular referneces.

- README.md
- package.json
Jest v23 [has been released](https://github.com/facebook/jest/blob/master/CHANGELOG.md#2300), but isn't allowed in the specified range as a peer dependency. This change expands the range to include v23, and also updates the version as a dev dependency to run tests on the latest version.
> fix(package): support jest v23

- __tests__/index.spec.js
- __tests__/integration.spec.js
- src/index.js
Hi there, this is my attempt to fix https://github.com/americanexpress/jest-image-snapshot/issues/61
- Have the "snapshot summary" with correct informations about _unmatched_ number of snapshots.
- Have the "u" & "i" usage suggestions in Jest watch mode. (update snapshot)
- I updated the counter of the "unmatched" snapshots in the singleton `snapshotState` when images differs.
- I also refactored a little the `updateSnapshotState`, I hope you don't mind... there was a mix between merging & assigning to the singleton (the one & only snapshotState Jest is aware of and bases its report on)
- Jest now displays the number of _unmatched_ snapshots + hints about the "u" to update snapshots.
- Edit a test, change the rendering, Jest should display `› 1 snapshot test failed in 1 test suite. …
> Display n° of unmatched snapshots in the snapshot summary + "u" usage suggestion

- src/diff-snapshot.js
Change now used process.execPath to ensure that we spawn a new node process to run diff-snapshot if node is not on the environment.
Closes #108
> fix(execution): used exec path to execute spawned diff-snapshot process

- README.md
- __tests__/__snapshots__/index.spec.js.snap
- __tests__/diff-snapshot.spec.js
- __tests__/index.spec.js
- src/diff-snapshot.js
- src/index.js
Allows a custom diff directory to be set, by passing the `customDiffDir` option.
Closes: #97
> feat(options): Add customDiffDir

- README.md
Just a minor detail. This wasn't rendered correctly on npm (https://www.npmjs.com/package/jest-image-snapshot), but worked on GitHub.
> fix formatting of headings

- .npmignore
Prevents folders such as `examples` and `__tests__` from being published in the package pushed to npm. This results in a small decrease in package size.
These folders do not influence the production code and were discovered after our Windows CI output the following when running `git clean -fxdq`:
```
warning: Could not stat path 'src/desktop/node_modules/jest-image-snapshot/examples/__tests__/__image_snapshots__/puppeteer-example-spec-js-jest-image-snapshot-usage-with-an-image-received-from-puppeteer-works-1-snap.png': Filename too long
```
> chore(npm): add npmignore

- README.md
Update example with `failureThreshold` to use a `number` instead of `string`. Inside the type definition of `MatchImageSnapshotOptions` the expected type is `number`.
[Link to the definition](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/jest-image-snapshot/index.d.ts#L52)
> docs: failureThreshold should be a number

- README.md
- __tests__/index.spec.js
- src/index.js
This allows it to use `jest-image-snapshot` in environments where it's not possible to spawn other processes (e.g. electron render process)
> feat(options): add option to run diff in process

- .npmignore
- README.md
- __tests__/__snapshots__/index.spec.js.snap
- __tests__/diff-snapshot.spec.js
- __tests__/index.spec.js
- package.json
- src/diff-snapshot.js
- src/index.js
As in readme - Applies Gaussian Blur on generated images. Useful when you have noise after scaling images per different resolutions on your target website.
My problem was that I received a lot of random pixel differences on the same images on website between different runs because of downscaling. Applying a blur, usually 1-2 radius, removes this noise and fixes this issue
> Add option to use blur on compared images

- README.md
Table of Contents ids didn't link to subsections of the readme.
> docs(readme/link): incorrect URL for Table of Contents

- .travis.yml
- package-lock.json
- package.json
- Updates jest dev dep to 25.1.0
- Relaxes peer dep to allow v25
- Drops node 6 and adds node 12
BREAKING CHANGE: Node min version is now 8
More info: https://jestjs.io/blog/2020/01/21/jest-25
Fixes #169
> chore(package): updating jest to 25.1.0 for perf improvements

- __tests__/diff-snapshot.spec.js
- src/diff-snapshot.js
Closes https://github.com/americanexpress/jest-image-snapshot/issues/182
> fix: dumpDiffToConsole base64 string output

- README.md
- __tests__/integration.spec.js
- package-lock.json
- package.json
> Based on feedback from #152 this would be precursor to a 3.0.0 release.
Upgrades pixelmatch & pngjs to latest releases.
https://github.com/mapbox/pixelmatch/releases/tag/v5.0.0
Noteworthy changes from the pixelmatch release notes:
* Improve matching performance by ~35%.
* Bypass detailed comparison when image data is identical, significantly improving performance.
* Fix anti-aliasing detection on image edges.
* Breaking: update to ES6 syntax, dropping Node <6.4 and IE11 support.
> chore(packages): Upgrade from pixelmatch 4.x to 5.x, and pngjs to 3.4

- .travis.yml
This would enable semantic-release to run on node 10. As node 8 is not supported by semantic-release.
https://github.com/semantic-release/semantic-release/blob/master/docs/support/node-version.md
> chore(travis): run semantic-release on node version 10

- __tests__/diff-snapshot.spec.js
- src/diff-snapshot.js
pixelmatch now [handles this for us](https://github.com/mapbox/pixelmatch/pull/60)
> perf(diff-snapshot): remove logic to bypass image diff for identical images

- README.md
Correct minor grammar error in README.md
> README.md: it's -> its

- README.md
- __tests__/diff-snapshot.spec.js
- src/diff-snapshot.js
if the option `allowSizeMismatch` is set, a build will not allways fail on
images with different sizes. Missing or Added Pixel will be counted as a
missmatch and respected by the set threshold.
Related #83, #85
-----
I am not sure if this addition is welcome because of the discussion in the issues mentioned but we needed to implement it anyway because we want our test to run on different operating systems which results in different image sizes if we crop images using 3rd party libraries. The reason for this is different shadow and text rendering of the operating systems and browsers.
> feat(options): add option to pass on size missmatch

- package.json
This updates the order of the semantic release plugins so semantic release bumps the package.json version.
> chore(release): update semantic-release plugin order

- README.md
- __tests__/__snapshots__/index.spec.js.snap
- __tests__/index.spec.js
- package.json
- src/index.js
Hi!
This PR fixes `noColors` option to allow chalk auto-detect colors support.
Also, I had to add `env FORCE_COLOR=1` to the pre-commit hook: `"pre-commit": "env FORCE_COLOR=1 npm test"`. For some reasons chalk doesn't detect colors on windows 10 when executed by husky (https://github.com/typicode/husky/issues/350) and tests don't pass.
Closes #114
> Fix no colors option

- README.md
**Description**
There is a type definition already created in DefinitelyTyped for TypeScript users. This PR adds a link to this package in the readme file so users can easily find the types.
**DefinitelyTyped npm package**
https://www.npmjs.com/package/@types/jest-image-snapshot
**DefinitelyTyped GitHub**
https://github.com/DefinitelyTyped/DefinitelyTyped#readme
> Docs(readme): Add link to DefinitelyTyped in read me file for TypeScript users

- README.md
- __tests__/__snapshots__/index.spec.js.snap
- __tests__/index.spec.js
- src/index.js
This MR implements support for iTerm's [Inline Images Protocol](https://iterm2.com/documentation-images.html) when the `dumpDiffToConsole` flag is set to `'inline'`.
The scope of this is admittedly narrow, but it may be useful to a wider audience.
> feat: inline images support (dumpDiffToConsole='inline')

- README.md
jest peerDependency in the README was updated to reflect the peerDeps in `package.json`
> Update Jest peerDependency in README installation

- src/index.js
Closes #243. See that issue for details.
When jest finishes, the statistics shown are wrong if some snapshots failed.
There are no existing tests that assert on what is reported to jest because `UNSTABLE_SKIP_REPORTING` is enabled.
I've tested this manually in a simple project. 
Stats reported to jest are now correct.
> fix incorrect stats reported to jest

- .github/workflows/tests.yml
- package-lock.json
- package.json
Update jest and associated jest dependencies to v28.
BREAKING CHANGE: Required dropping Node 10 support since jest [dropped support](https://jestjs.io/blog/2022/04/25/jest-28#breaking-changes) and now uses [`globalThis`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/globalThis), which is only available in Node >=12.0.0 (see [actions log with Node 10 failure](https://github.com/aarongoldenthal/jest-image-snapshot/runs/6299403896?check_suite_focus=true)). For consistency, updated `engines.node` to mirror `jest` (`^12.13.0 || ^14.15.0 || ^16.10.0 || >=17.0.0`), which includes leaving Node 12 compatibility (even though it went end-of-life on 2022-04-30). Also updated `tests` actions to drop Node 10 and add Node 17 and 18.
I did not notice any Jest v28 …
> chore: upgrade jest to v28 (#296)

- __tests__/index.spec.js
- package-lock.json
- package.json
- src/index.js
Bumps [chalk][1] from `^1.1.3` to `^4.0.0`.
- [Release notes](https://github.com/chalk/chalk/releases)
- [v2.0.0](https://github.com/chalk/chalk/releases/tag/v2.0.0)
- [v3.0.0](https://github.com/chalk/chalk/releases/tag/v3.0.0)
- [v4.0.0](https://github.com/chalk/chalk/releases/tag/v4.0.0)
- [Commits](https://github.com/chalk/chalk/compare/v1.1.3...v4.0.0)
Chalk's major changes were:
- Minimum required Node version is Node v10 (v4)
- `chalk.constructor` has been replaced with `chalk.Instance` (v3)
- `chalk.enabled` has been replaced with `chalk.level` (v3)
[1]: https://www.npmjs.com/package/chalk
Jest v28 uses Chalk v4 as a dependency, so using the same version in jest-image-snapshot will mean users only need to download one version of chalk.
`jest` tests pass.
I've tried testing this …
> chore(deps): bump chalk from `^1.1.3` to `^4.0.0`

- .github/workflows/health-check.yml
- .github/workflows/release.yml
- README.md
- __tests__/__snapshots__/diff-snapshot.spec.js.snap
- __tests__/__snapshots__/index.spec.js.snap
- package-lock.json
- package.json
Add support for Jest v29.
Jest v29 drops support for Node v12/v17, so I've updated the package.json to contain the same Node support as Jest.
The only other major breaking change in Jest v29 is that the default snapshot format has changed slightly, but that only changes the stored jest snapshots slighty (see https://jestjs.io/blog/2022/08/25/jest-29).
**BREAKING CHANGE: Drop support for Node v12 and Node v17, as Jest v29 does not support these versions.**
Resolves #308
I've tried testing this branch on [my own project (remark-mermaid-dataurl)](https://github.com/aloisklink/remark-mermaid-dataurl) using the following, and it seems to work fine.
```json
"jest": "^29.0.0",
"jest-image-snapshot": "git+https://github.com/aloisklink/jest-image-snapshot.git#chore/update-jest-to-v29",
```
- …
> chore(jest)!: add support for jest v29

- package.json
Resolves #313.
Makes `jest` peerDependency less strict, because some other testing libraries also support that `jest.extend` interface apparently (according to #313).
I was passing by that issue and decided to help. 🤷‍♂️ 
This is a relatively trivial change.
The library still would warn about incorrect Jest versions but it should not complain about Jest not being installed.
> build: make jest optional peerDependency

- __tests__/diff-snapshot.spec.js
- package-lock.json
- package.json
- src/diff-snapshot.js
Removes mkdirp from the project and replace it with Node's native recursive directory creation.
The `recursive: true` option is supported since Node v10.12.0 and is recommended by mkdirp since version [1.0](https://github.com/isaacs/node-mkdirp/blob/main/CHANGELOG.md#10):
> - Use native `fs.mkdir(path, { recursive: true })` when available.
- One less dependency to be managed by jest-image-snapshot
- This version of mkdirp is very outdated
```
System:
OS: Linux 5.19 Ubuntu 22.04.2 LTS 22.04.2 LTS (Jammy Jellyfish)
CPU: (8) x64 Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
Memory: 7.29 GB / 31.23 GB
Container: Yes
Shell: 5.1.16 - /bin/bash
```
All unit tests are passing with Node 14.15.0 (least supported version), 16.20.0 (latest v16) and 18.15.0 (latest v18).
None.
> chore: remove mkdirp in favor of recursive fs.mkdir

- .github/workflows/health-check.yml
- .github/workflows/release.yml
- .github/workflows/tests.yml
- __tests__/index.spec.js
This PR adds a matrix to run the CI on Windows, Mac, and Linux, and fixes a broken test on windows because of a different path name
To stop operating system regressions and allow for testing the repository in a Windows development environment.
Very little - this stops possible regressions in path systems, as what happened with https://github.com/privatenumber/pkgroll/issues/10
> ci: windows & mac
